# Generated by Django 6.1.1 on 2026-10-02 12:39

import slsiders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slsider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان اسلایدر')),
                ('link', models.URLField(verbose_name='لینک اسلایدر')),
                ('description', models.TextField(verbose_name='توضیحات اسلایدر')),
                ('image', models.ImageField(blank=True, null=True, upload_to=slsiders.models.upload_image, verbose_name='آپلود عکس')),
                ('active', models.BooleanField(default=True, verbose_name='فعال /غیر فعال')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدر ها',
            },
        ),
    ]
