# Generated by Django 6.1.1 on 2026-09-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_slug'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'تگ/برچسب', 'verbose_name_plural': 'تگ ها / برچسب ها'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='active',
            field=models.BooleanField(default=True, verbose_name='فعال/غیر فعال'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='products',
            field=models.ManyToManyField(to='products.product', verbose_name='اتصال به محصولات'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, verbose_name='عنوان در آدرس url'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
    ]
