# Generated by Django 6.1.1 on 2026-10-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_alter_tag_options_alter_tag_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True, verbose_name='عنوان در آدرس url'),
        ),
    ]
