# Generated by Django 6.1.1 on 2026-09-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
