# Generated by Django 6.1.1 on 2026-10-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_productcategory_options'),
        ('products', '0004_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='category.productcategory', verbose_name='اضافه کردن دسته بندی'),
        ),
    ]
